name: Continuous Deployment

on: "push"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: "npm ci --ignore-scripts"
        env:
          REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}
      - run: "npm run lint"

  test:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: "npm ci --ignore-scripts"
        env:
          REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}
      - run: "npm run test:unit"

  deploy-prod:
    name: Build and Deploy (production)
    if: github.ref == 'refs/heads/master'
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: "npm ci --ignore-scripts"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}
      - run: "npm rebuild && npm run prepare --if-present"
      - run: "npm run build"
      - run: "flyctl secrets set GIT_COMMIT $GITHUB_SHA"
      - run: "npm run deploy"
        env:
          REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}