name: Continuous Deployment

on: "push"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: "npm ci"
      - run: "npm run lint"

  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    env:
      REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: "npm ci"
      - run: "npm run test"

  deploy-prod:
    name: Build and Deploy (production)
    if: github.ref == 'refs/heads/master'
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: "npm ci"
        env:
          REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "secrets set GIT_COMMIT=$GITHUB_SHA"
        env:
          REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}
          FLY_ACCESS_TOKEN: ${{ secrets.FLYCTL_ACCESS_TOKEN }}
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --build-arg REMIX_TOKEN=${REMIX_TOKEN}"
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLYCTL_ACCESS_TOKEN }}
          REMIX_TOKEN: ${{ secrets.REMIX_AUTH_TOKEN }}